apps:
  - script     : ./bin/www
    name       : 'services'
    exec_mode  : cluster
    error_file : ./logs/services.log
    out_file   : ./logs/services.log
    merge_logs : true
    pid_file   : ./services.pid
