AWSTemplateFormatVersion: 2010-09-09
Description: Template for expense app support resources

Parameters:
  Stage:
    Type: String
    Description: Deployment environment (e.g., dev, test, or prod)
    AllowedValues:
      - dev
      - test
      - prod

Conditions:
  ProdDeployment: !Equals
    - !Ref Stage
    - prod

Resources:
  deployments:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !If
        - ProdDeployment
        - case-consulting-expense-app-deployments-prod
        - !Join
          - ''
          - - case-expense-app-deployments-
            - !Ref Stage
      LifecycleConfiguration:
        Rules:
          - Id: Remove previous deployment versions
            ExpirationInDays: 60
            Status: Enabled
      LoggingConfiguration:
        DestinationBucketName: !If
          - ProdDeployment
          - case-consulting-expense-app-logs-prod
          - !Join
            - ''
            - - case-expense-app-logs-
              - !Ref Stage
        LogFilePrefix: s3-logs/deployments/
      Tags:
        - Key: Application
          Value: expense-app
        - Key: Stage
          Value: !Ref Stage
